parameters:
    effiana_cache.effiana_data_cache_manager.class:                    Effiana\CacheBundle\Manager\EffianaDataCacheManager

services:
    effiana_cache.effiana_data_cache_manager:
        class: '%effiana_cache.effiana_data_cache_manager.class%'

    effiana_cache.provider.validation:
        public: false
        parent: effiana.cache.abstract
        calls:
            - [ setNamespace, [ 'validation' ] ]

    effiana_cache.validation_cache.doctrine:
        public: false
        class: Symfony\Component\Validator\Mapping\Cache\DoctrineCache
        arguments:
            - '@effiana_cache.provider.validation'

    effiana_cache.annotations:
        public: false
        parent: effiana.cache.abstract
        calls:
            - [ setNamespace, [ 'effiana_annotations_cache' ] ]

    effiana_cache.serializer:
        public: false
        parent: effiana.cache.abstract
        calls:
            - [ setNamespace, [ 'effiana_serializer_cache' ] ]

    effiana_cache.jms_serializer:
        public: false
        parent: effiana.cache.abstract
        calls:
            - [ setNamespace, [ 'jms_serializer_cache' ] ]

    effiana.cache.memory_cache_chain:
        public: false
        class: Effiana\CacheBundle\Provider\MemoryCacheChain

    effiana.cache.configuration_loader:
        class: Effiana\CacheBundle\Loader\ConfigurationLoader
        calls:
            - [ setParameterBag, ['@=service("kernel").getContainer().getParameterBag()']]
