parameters:
    effiana_cache.oro_data_cache_manager.class:                    Effiana\CacheBundle\Manager\OroDataCacheManager

services:
    effiana_cache.oro_data_cache_manager:
        class: '%effiana_cache.oro_data_cache_manager.class%'

    effiana_cache.provider.validation:
        public: false
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'validation' ] ]

    effiana_cache.validation_cache.doctrine:
        public: false
        class: Symfony\Component\Validator\Mapping\Cache\DoctrineCache
        arguments:
            - '@effiana_cache.provider.validation'

    effiana_cache.annotations:
        public: false
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'oro_annotations_cache' ] ]

    effiana_cache.serializer:
        public: false
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'oro_serializer_cache' ] ]

    effiana_cache.jms_serializer:
        public: false
        parent: oro.cache.abstract
        calls:
            - [ setNamespace, [ 'jms_serializer_cache' ] ]

    effiana_cache.jms_serializer_adapter:
        public: false
        class: 'Metadata\Cache\DoctrineCacheAdapter'
        arguments:
            - 'jms_serializer_cache'
            - '@effiana_cache.jms_serializer'

    effiana_cache.action.handler.invalidate_scheduled:
        class: 'Effiana\CacheBundle\Action\Handler\InvalidateCacheActionScheduledHandler'
        arguments:
            - '@oro_cron.deferred_scheduler'
            - '@effiana_cache.action.handler.schedule_arguments_builder'
            - '@effiana_cache.action.transformer.datetime_to_cron_format'

    effiana_cache.action.handler.schedule_arguments_builder:
        class: 'Effiana\CacheBundle\Action\Handler\InvalidateCacheScheduleArgumentsBuilder'
        public: false

    effiana_cache.action.provider.invalidate_cache_time:
        class: 'Effiana\CacheBundle\Action\Provider\InvalidateCacheTimeProvider'
        arguments:
            - '@effiana_cache.action.handler.schedule_arguments_builder'
            - '@oro_cron.schedule_manager'
            - '@effiana_cache.action.transformer.datetime_to_cron_format'

    effiana_cache.action.transformer.datetime_to_cron_format:
        public: false
        class: 'Effiana\CacheBundle\Action\Transformer\DateTimeToCronFormatTransformer'

    oro.cache.memory_cache_chain:
        public: false
        class: Effiana\CacheBundle\Provider\MemoryCacheChain

    oro.cache.configuration_loader:
        class: Effiana\CacheBundle\Loader\ConfigurationLoader
        calls:
            - [ setParameterBag, ['@=service("kernel").getContainer().getParameterBag()']]
